language: php
dist: trusty
os: linux

services:
  - docker

addons:
  chrome: stable
  firefox: latest

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="chrome"
    - DRIVER_OPTIONS='{"args":["headless", "no-sandbox","window-size=1024,768"]}'
    - CHROMEDRIVER_VERSION="latest"
    - GECKODRIVER_VERSION="latest"
    - START_XVFB="1"
    - COMPOSER_FLAGS=""
    - DRIVER_URL=http://localhost:4444
    - WEB_FIXTURES_HOST=http://localhost:8002

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - php: 7.3 # XVFB with regular Chrome (not headless)
      env:
        - BROWSER_NAME="chrome"
        - DRIVER_OPTIONS='{"args":["no-sandbox","window-size=1024,768"]}'
        - START_XVFB=1
    - php: 7.3 # XVFB with regular Firefox (not headless)
      env:
        - BROWSER_NAME="firefox"
        - DRIVER_OPTIONS='{}'
          START_XVFB=1
    - php: 7.3 # Headless Firefox
      env:
        - BROWSER_NAME="firefox"
        - DRIVER_OPTIONS='{"args":["-headless"]}'
          START_XVFB=0

before_install:
  - chmod +x ./.build/before_install.sh
  - ./.build/before_install.sh

install:
  - chmod +x ./.build/install.sh
  - ./.build/install.sh

before_script:
  - chmod +x ./.build/before_script.sh
  - ./.build/before_script.sh

script:
  - chmod +x ./.build/script.sh
  - ./.build/script.sh

after_script:
  - chmod +x ./.build/after_script.sh
  - ./.build/after_script.sh

after_failure:
  - if [ -f ./logs/webdriver.log ]; then cat ./logs/webdriver.log; fi
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/mink-test-server.log ]; then cat ./logs/mink-test-server.log; fi
